name: Generate Vocabulary

on:
  push:
    paths: [
      .github/workflows/generate-vocabulary.yml,
      scripts/generate-vocabulary.ts,
      src/**
    ]

jobs:
  generate-vocab:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        level: [A1, A2]
        count: [5]
        sourceLang: [fr]
        targetLang: [de]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - run: npm run build

      - name: Generate vocabulary
        run: |
          node dist/scripts/generate-vocabulary.js \
            ${{ matrix.count }} \
            ${{ matrix.level }} \
            ${{ matrix.sourceLang }} \
            ${{ matrix.targetLang }} \
            data/${{ matrix.sourceLang }}-${{ matrix.targetLang }}/${{ matrix.level }}
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
            
      - name: 💾 Commit generated vocabulary file
        run: |
          git pull
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/${{ matrix.sourceLang }}-${{ matrix.targetLang }}/${{ matrix.level }}/*
          git diff --quiet && git diff --staged --quiet || git commit -m "📚 Add vocabulary"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
