name: Upload Video

on:
  push:
    paths: [
      .github/workflows/upload-video.yml,
      scripts/upload-video.ts,
      .credentials/*
    ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  upload-video:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        level: [A1]
        sourceLang: [fr]
        targetLang: [de]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install

      - run: npm run build

      - name: Upload video
        run: |
          node dist/scripts/upload-video.js \
            ${{ matrix.level }} \
            data/${{ matrix.sourceLang }}-${{ matrix.targetLang }}/${{ matrix.level }}
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: 💾 Commit updated file
        if: success()
        run: |
          git pull
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .credentials/*
          git diff --quiet && git diff --staged --quiet || git commit -m "Update credentials"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
